# Generated by Django 4.2.17 on 2025-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_load_core_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="numbering",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
