# Generated by Django 4.2.17 on 2025-06-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_label_numbering"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief explanation of the category."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display (e.g., 1 for 'Content', 2 for 'Exam Management').",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Study Skill Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief explanation of the skill."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display within the category."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.studyskillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
