# Generated by Django 4.2.17 on 2025-05-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_label_numbering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("slides", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slide",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="slide",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="slide",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="slide",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.curriculum",
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.language",
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="title",
            field=models.CharField(default="Unkown", max_length=255),
        ),
        migrations.AddField(
            model_name="slide",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.label",
            ),
        ),
        migrations.AddField(
            model_name="slide",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="SlideBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Ordre du bloc dans la présentation"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="ex: 'basic', 'two-column'", max_length=50
                    ),
                ),
                ("content_html", models.TextField(blank=True)),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="slides.slide",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("slide", "order")},
            },
        ),
        migrations.RemoveField(
            model_name="slide",
            name="content_html",
        ),
        migrations.RemoveField(
            model_name="slide",
            name="order",
        ),
        migrations.RemoveField(
            model_name="slide",
            name="slideshow",
        ),
        migrations.RemoveField(
            model_name="slide",
            name="template_name",
        ),
        migrations.DeleteModel(
            name="Slideshow",
        ),
    ]
