# Generated by Django 4.2.17 on 2025-05-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_label_numbering"),
        ("slides", "0002_alter_slide_options_alter_slide_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="slide",
            unique_together={("language", "curriculum", "subject", "topic")},
        ),
    ]
