# Generated by Django 4.2.17 on 2025-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0003_alter_slide_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slide",
            options={"verbose_name": "Slideshow", "verbose_name_plural": "Slideshows"},
        ),
        migrations.AlterModelOptions(
            name="slideblock",
            options={
                "ordering": ["order"],
                "verbose_name": "Slide Block",
                "verbose_name_plural": "Slide Blocks",
            },
        ),
        migrations.AlterField(
            model_name="slide",
            name="title",
            field=models.CharField(default="Unknown Slideshow Title", max_length=255),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Order of the block in the slideshow"
            ),
        ),
        migrations.AlterField(
            model_name="slideblock",
            name="template_name",
            field=models.CharField(
                help_text="e.g., 'basic', 'two-column'", max_length=50
            ),
        ),
    ]
