# Generated by Django 4.2.17 on 2025-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0004_alter_slide_options_alter_slideblock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
