# Generated by Django 4.2.17 on 2025-05-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_label_numbering"),
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("language", "curriculum", "subject", "topic")},
        ),
    ]
