# Generated by Django 4.2.17 on 2025-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
