# Generated by Django 4.2.17 on 2025-06-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_label_numbering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_recipe_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                help_text="The unique title of the recipe.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific topic or chapter this recipe covers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.label",
            ),
        ),
        migrations.AlterField(
            model_name="recipeblock",
            name="content_html",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipeblock",
            name="order",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="recipeblock",
            name="template_name",
            field=models.CharField(max_length=100),
        ),
    ]
