# Generated by Django 4.2.17 on 2025-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_options_alter_recipe_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeblock",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_images/"),
        ),
        migrations.AlterField(
            model_name="recipeblock",
            name="content_html",
            field=models.TextField(blank=True),
        ),
    ]
