# Generated by Django 4.0.5 on 2024-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
            preserve_default=False,
        ),
    ]
