# Generated by Django 4.0.5 on 2024-12-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='level',
            new_name='parent',
        ),
    ]
