# Generated by Django 4.2.17 on 2025-05-28 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduledsession",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Scheduled Session",
                "verbose_name_plural": "Scheduled Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="studyplan",
            options={"ordering": ["student", "-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="studyplan",
            name="curriculum",
        ),
        migrations.AlterField(
            model_name="scheduledsession",
            name="subject_color",
            field=models.CharField(default="#808080", max_length=7),
        ),
        migrations.AlterField(
            model_name="scheduledsession",
            name="subject_local_id",
            field=models.IntegerField(
                blank=True, help_text="Links to localId in config.subjects", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text="Configuration of subjects, exam dates, priorities, availability...",
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="name",
            field=models.CharField(
                help_text="Name of the plan, e.g., 'May 2025 Revisions'", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plans_planner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
