# Generated by Django 4.2.17 on 2025-06-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planner", "0002_alter_scheduledsession_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studyplan",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="studyplan",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="name",
            field=models.CharField(
                default="My Study Plan",
                help_text="Descriptive name for the plan, e.g., 'Spring Term Revisions'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plan_planner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
